version: "3"

services:
  database:
    container_name: puti-db
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ${PUTI_ROOT}${MYSQL_DATA_PATH}:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      - ${PUTI_ROOT}${MYSQL_LOG_PATH}:/var/log/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    restart: always
    networks:
      - db
    # this entrypoint and command can rewrite by entrypoint script
    entrypoint: ""
    command: bash -c "chown -R mysql:mysql /var/log/mysql && exec /entrypoint.sh mysqld"

  puti:
    container_name: puti
    image: puti/puti:${PUTI_VERSION}
    depends_on:
      - database
    volumes:
      - ${PUTI_ROOT}${PUTI_DATA_PATH}:/data/puti
      - ${PUTI_ROOT}${PUTI_LOG_PATH}:/data/logs/puti
    ports:
      - "${PUTI_HTTP_PORT_OUT}:${PUTI_HTTP_PORT}"
      - "${PUTI_HTTPS_PORT_OUT}:${PUTI_HTTPS_PORT}"
    restart: always
    networks:
      - db
    entrypoint: ["/usr/local/bin/wait-for-db.sh", "database:3306", "--", "docker-entrypoint.sh"]
    command: ["puti"]

networks:
  db:
